name: package_template
channels:
- defaults
- conda-forge
dependencies:
- "python>=3.8"
- numpy
- scipy
- scikit-learn
- matplotlib
- pandas
- jupyterlab
- pytest
- pytest-cov
- coveralls
- autopep8
- black
- isort
